{{- if not .Values.existingSecret.name -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pingdom-exporter.secretName" . }}
  {{- if .Values.secret.annotations }}
  annotations:
    {{- toYaml .Values.secret.annotations | nindent 4 }}
  {{- end }}
  labels:
    {{- include "pingdom-exporter.labels" . | nindent 4 }}
type: Opaque
data:
  apiToken: {{ .Values.pingdom.apiToken | b64enc }}
{{- end }}
