name: Check pull request

on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Get all git tags
      run: git fetch --prune --unshallow --tags

    - uses: actions/setup-go@v3
      with:
        go-version: '>=1.17.0'

    - name: Run tests
      run: make test

    - name: Build Docker image
      run: make image REPO=${{GITHUB_REPOSITORY_OWNER}} IMAGE_EXTRA_ARGS='--label "runnumber=${GITHUB_RUN_ID}"'
